name: Replexica
description: Accurate AI localization for web & mobile apps.
author: Replexica

runs:
  using: 'docker'
  image: 'action/Dockerfile'

branding:
  icon: './content/logo.png'
  color: 'black'
