name: Claude Issue Autolabeling

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to label'
        required: false
        type: string

jobs:
  autolabel:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Repository Labels
        id: labels
        run: |
          labels=$(gh label list --limit 100 --json name,description --jq 'map("\(.name) (\(.description))") | join(", ")')
          echo "available_labels=$labels" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Target Issue
        id: target_issue
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.issue_number }}" ]]; then
            echo "issue_number=${{ github.event.inputs.issue_number }}" >> $GITHUB_OUTPUT
            issue_data=$(gh issue view ${{ github.event.inputs.issue_number }} --json title,body)
            echo "issue_title=$(echo "$issue_data" | jq -r '.title')" >> $GITHUB_OUTPUT
            echo "issue_body=$(echo "$issue_data" | jq -r '.body')" >> $GITHUB_OUTPUT
          else
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
            echo "issue_title=${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
            echo "issue_body=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Autolabel Issue
        id: claude_analysis
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_ANTHROPIC_API_KEY }}
          timeout_minutes: "5"
          allowed_tools: "Bash"
          direct_prompt: |
            Analyze this newly created issue and apply appropriate labels using the gh CLI.

            Available repository labels: ${{ steps.labels.outputs.available_labels }}

            Tasks:
            1. Analyze the issue content
            2. Use `gh issue edit ${{ steps.target_issue.outputs.issue_number }} --add-label "label-name"` to apply each relevant label
            3. Add a comment explaining your labeling decisions

            Requirements:
            - Apply ALL relevant labels that match the issue content
            - If no labels are truly relevant, apply NO labels at all
            - Be thorough but precise - don't force labels that don't fit
            - Use the Bash tool to run gh commands WITHOUT asking for confirmation
            - The GITHUB_TOKEN is already set in the environment for gh authentication

            Issue Title: ${{ steps.target_issue.outputs.issue_title }}
            Issue Body: ${{ steps.target_issue.outputs.issue_body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

